import numpy as np
from numpy.typing import NDArray

def num_pairs(N: int) -> int: ...
def pair_to_index(i: int, j: int, N: int) -> int: ...
def inverse_distance_upper(R: NDArray[np.float64], eps: float = 1e-12) -> NDArray[np.float64]: ...
def inverse_distance_upper_and_jacobian(
    R: NDArray[np.float64], eps: float = 1e-12
) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...
