# .github/workflows/release.yml
name: Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04] # macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"   # host Python, cibuildwheel makes all others

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.*

      - name: Build wheels
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_SKIP: "pp* *-musllinux_*"   # skip PyPy, musllinux if you want
          CIBW_TEST_COMMAND: "pytest -q {project}/tests -k 'not slow' -x"
          CIBW_TEST_EXTRAS: "test"
          CIBW_ENVIRONMENT: >
            OMP_NUM_THREADS=1
            MKL_THREADING_LAYER=SEQUENTIAL
            MKL_INTERFACE_LAYER=LP64
          CIBW_BEFORE_ALL_LINUX: >
            bash -euxo pipefail -c '
              source /etc/os-release || true
              if command -v yum >/dev/null 2>&1; then
                yum install -y epel-release || true
                yum install -y openblas-devel gcc-gfortran pkgconfig
              elif command -v dnf >/dev/null 2>&1; then
                dnf install -y epel-release || true
                dnf install -y "dnf-command(config-manager)" || true
                dnf config-manager --set-enabled crb || true   # enable powertools/CRB
                dnf install -y openblas-devel gcc-gfortran pkgconf-pkg-config
              elif command -v microdnf >/dev/null 2>&1; then
                microdnf install -y openblas-devel gcc-gfortran pkgconf-pkg-config || exit 1
              else
                echo "No supported package manager found" >&2; exit 1
              fi
            '
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist
        run: python -m pip install build && python -m build --sdist -o wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*

  publish:
    needs: build-wheels
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.11.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

