# .github/workflows/release.yml
name: Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04] # macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"   # host Python, cibuildwheel makes all others

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.*

      - name: Build wheels
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_SKIP: "pp* *-musllinux_*"   # skip PyPy, musllinux if you want
          CIBW_TEST_COMMAND: "pytest -q {project}/tests -k 'not slow' -x"
          CIBW_TEST_EXTRAS: "test"
          CIBW_ENVIRONMENT: >
            OMP_NUM_THREADS=1
            OPENBLAS_NUM_THREADS=1
            MKL_THREADING_LAYER=SEQUENTIAL
            MKL_INTERFACE_LAYER=LP64
          CIBW_BEFORE_BUILD_LINUX: |
            pip install scipy-openblas32
            ls -l $(python -c "import scipy_openblas32, os; print(os.path.dirname(scipy_openblas32.__file__))")
            OPENBLAS_DIR=$(python -c "import scipy_openblas32, os; print(os.path.dirname(scipy_openblas32.__file__))")
            echo "CMAKE_ARGS=-DBLAS_LIBRARIES=$OPENBLAS_DIR/libopenblas.so -DBLAS_INCLUDE_DIR=$OPENBLAS_DIR" > /tmp/cmake_args.env
          CIBW_ENVIRONMENT_LINUX: |
            LD_LIBRARY_PATH=$LD_LIBRARY_PATH
            $(cat /tmp/cmake_args.env)
            OPENBLAS_NUM_THREADS=1
            OMP_NUM_THREADS=1
          CIBW_ENVIRONMENT_PASS_LINUX: "LD_LIBRARY_PATH CMAKE_ARGS"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist
        run: python -m pip install build && python -m build --sdist -o wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*

  publish:
    needs: build-wheels
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.11.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

