# .github/workflows/release.yml
name: Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04] # macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"   # host Python, cibuildwheel makes all others

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.*

      - name: Build wheels
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_SKIP: "pp* *-musllinux_*"   # skip PyPy, musllinux if you want
          CIBW_TEST_COMMAND: "pytest -q {project}/tests -k 'not slow' -x"
          CIBW_TEST_EXTRAS: "test"
          CIBW_ENVIRONMENT: >
            OMP_NUM_THREADS=1
            MKL_THREADING_LAYER=SEQUENTIAL
            MKL_INTERFACE_LAYER=LP64
          CIBW_BEFORE_ALL_LINUX: >
            bash -euxo pipefail -c '
              OB_VER=0.3.26
              curl -L https://github.com/xianyi/OpenBLAS/archive/refs/tags/v${OB_VER}.tar.gz | tar xz
              cd OpenBLAS-${OB_VER}
              # Build a static, PIC, pthreads-only OpenBLAS with CPU dispatch
              make -j"$(nproc)" NO_SHARED=1 DYNAMIC_ARCH=1 USE_OPENMP=0 NO_AFFINITY=1 \
                   CFLAGS="-fPIC -O3" FCFLAGS="-fPIC -O3"
              make install PREFIX=/opt/openblas
              ls -l /opt/openblas/lib
            '
          CIBW_ENVIRONMENT_LINUX: >
            KF_USE_OPENBLAS=ON
            OPENBLAS_DIR=/opt/openblas
            OMP_NUM_THREADS=1
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist
        run: python -m pip install build && python -m build --sdist -o wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*

  publish:
    needs: build-wheels
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.11.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

